### PR TITLE
Improve init

### PR DESCRIPTION
**Pull request by dsodx**

### CODE REVIEW

**Review by DiorDS — COMMENTED** [review]
I`m a litle bit dumb)

**Comment by DiorDS** [comment]
Run pylint plan_renderer
************* Module plan_renderer
plan_renderer/__init__.py:11:4: E0605: Invalid format for __all__, must be tuple or list (invalid-all-format)

-----------------------------------
Your code has been rated at [8](https://github.com/DiorDS/tg_shedule_create/actions/runs/5304400392/jobs/9600693186#step:5:9).65/[10](https://github.com/DiorDS/tg_shedule_create/actions/runs/5304400392/jobs/9600693186#step:5:11)

Error: Process completed with exit code 2.


Make

**Comment by dsodx** [comment]
Так у меня тупл там

**Comment by DiorDS** [comment]
__all__ = (
    "Renderer",
)

**Comment by dsodx** [comment]
я уже понял

**Comment by dsodx** [comment]
ты бы мог пофиксить(

**Pull request merged**
